server.port=8080

# PostgreSQL Database
spring.datasource.url=jdbc:postgresql://postgres:5432/transcoder
spring.datasource.username=transcoder
spring.datasource.password=transcoder123
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# File paths
app.videos.input-dir=/app/videos/input
app.videos.output-dir=/app/videos/output

# File upload
spring.servlet.multipart.max-file-size=2GB
spring.servlet.multipart.max-request-size=2GB

# JWT
app.jwt.secret=MyVideoTranscoderSuperSecretKeyThatIsAtLeast256BitsLong2026
app.jwt.expiration-ms=86400000

# CMS
app.cms.poster-dir=/app/posters
app.cms.subtitle-dir=/app/videos/input/subtitles
app.cms.dub-dir=/app/videos/input/dub
